CREATE TABLE experience (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title TEXT,
    timePeriod TEXT,
    location TEXT,
    description TEXT
);

INSERT INTO experience(title, timePeriod, location, description) VALUES ("University of Georgia SSRL MOCI Mission Operations Team Lead", "January 2020 - Present", "Athens, Georgia", "As the Missions Operations Team Lead for MOCI, a 6U CubeSat at the University of Georgia's Small Satellite Research Laboratory, I get the opportunity to lead ground station software and system testing. Planning out Day-in-the-Life Tests, creating mission schedules, drawing up and maintainging the Concept of Operations document, and satellite communications are just a few of the things that I get the opportunity to do as I lead my team of students toward the desired end goal: mission success.");
INSERT INTO experience(title, timePeriod, location, description) VALUES ("University of Georgia SSRL Simulation Manager", "April 2018 - January 2020", "Athens, Georgia", "Before being promoted to Mission Operations Team Lead, I spent my time working as the Small Satellite Research Laboratory's simulation manager. Using <a href='https://www.agi.com/products/stk'>AGI's Systems Tool Kit</a> (STK), I was able to plan orbital paths, run power simulations, and create satellite schedules. Seeing a need for the automation of many of these processes, I began the development of a custom Python Package. STKHelper, as it came to be called, utilizes the STK Python API to create a better user experience. It can be installed from the <a href='https://pypi.org/project/stkhelper/'>PyPi</a> or directly from <a href='https://github.com/cnmcferren/stkhelper'>GitHub.</a>");
INSERT INTO experience(title, timePeriod, location, description) VALUES ("Lockheed Martin Skunk Works Intern in Advanced Algorithms", "May 2020 - August 2020", "Fort Worth, Texas", "By working in the Skunk Works Advanced Algorithms Department within the Lockheed Martin Corperation, I was able to push my boundaries by diving into optimization of legacy code and GPU programming with Nvidia's CUDA C++ API. Using CUDA C++, I was able to substantially speed up Threat Detection processing times by parellizing the cacluations.");
INSERT INTO experience(title, timePeriod, location, description) VALUES ("Researcher in the UGA Department of Physics & Astronomy", "May 2016 - December 2016", "Athens, Georgia", "For two semesters, I worked as a highschool intern in the Department of Physics & Astronomy. Initially starting my work researching debris disk development in binary star systems, we later shifted our focus to age dating stars using Gyrochronology. Through this, I was able to gain experience with research by analyzing observatory images from the University of Hawaii and using Python accompanied with other softwares to estimate stellar rotational periods.");
